backend:
  name: github
  repo: rezawin8410-ux/rezawin8410-ux.github.io
  branch: main
  base_url: https://api.github.com
  auth_endpoint: auth
  client_id: Ov23ctqW9jNrWNdyv47Z
  client_secret: 91bc53324f74a4c708012ca8db037f82748b2195

site_domain: rezawin8410-ux.github.io
media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "settings"
    label: "ØªÙ†Ø¸ÛŒÙ…Ø§Øª Ø³Ø§ÛŒØª"
    files:
      - name: "general"
        label: "Ø§Ø·Ù„Ø§Ø¹Ø§Øª Ø§ØµÙ„ÛŒ"
        file: "_data/settings.json"
        fields:
          - {label: "Ø¹Ù†ÙˆØ§Ù† ØµÙØ­Ù‡ Ø§ÙˆÙ„", name: "heroTitle", widget: "string", default: "Ù…Ø¨Ù„ØŒ ØªØ´Ú©ØŒ ÙØ±Ø´ â†’ Ù…Ø«Ù„ Ø±ÙˆØ² Ø§ÙˆÙ„Ø´ Ú©Ù†!"}
          - {label: "Ø´Ù…Ø§Ø±Ù‡ ØªÙ…Ø§Ø³ Ø§ÙˆÙ„", name: "tel1", widget: "string", default: "09148178410"}
          - {label: "Ø´Ù…Ø§Ø±Ù‡ ØªÙ…Ø§Ø³ Ø¯ÙˆÙ…", name: "tel2", widget: "string", default: "09104415400"}
          - {label: "Ù…ØªÙ† Ø¨Ù†Ø± ØªØ®ÙÛŒÙ", name: "bannerText", widget: "text", default: "ğŸ Ø§Ù…ØªÛŒØ§Ø² Ø´Ø³ØªØ´ÙˆÛŒ Ù…Ø¨Ù„ Ø±Ø§ÛŒÚ¯Ø§Ù† Ø¨Ú¯ÛŒØ±!"}

  - name: "prices"
    label: "Ø¬Ø¯ÙˆÙ„ Ù‚ÛŒÙ…Øªâ€ŒÙ‡Ø§"
    folder: "_data/prices"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Ù†Ø§Ù… Ø¢ÛŒØªÙ…", name: "title", widget: "string"}
      - {label: "Ù‚ÛŒÙ…Øª ÙˆØ§Ù‚Ø¹ÛŒ (ØªÙˆÙ…Ø§Ù†)", name: "original", widget: "number"}
      - {label: "Ù‚ÛŒÙ…Øª Ø¨Ø§ ØªØ®ÙÛŒÙ (ØªÙˆÙ…Ø§Ù†)", name: "final", widget: "number"}

  - name: "gallery"
    label: "ØªØµØ§ÙˆÛŒØ± Ú¯Ø§Ù„Ø±ÛŒ"
    folder: "_data/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Ø¹Ù†ÙˆØ§Ù† Ø¹Ú©Ø³", name: "title", widget: "string"}
      - {label: "Ø¢Ù¾Ù„ÙˆØ¯ Ø¹Ú©Ø³", name: "image", widget: "image"}
